apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-resourcequota
  namespace: tenant-b
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8GI
    limits.cpu: "4"
    limits.memory: 8Gi
    ppods: "10"