apiVersion: v1
kind: Deployment
metadata:
  name: monolith
  namespace: fonbank-legacy
  labels:
    app: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
   metadata:
    labels:
      app: monolith
   spec:
     containers:
       - name: monolith
         image: finbank/monolith:v1
         ports:
           - containerPort: 8080
         env:
           - name: DB_HOST
             value: postgres
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                 key: POSTGRES_DB
                 name: postgres-secret
           - name: DB_USER
             valueFrom:
               secretKeyRef:
                 key: POSTGRES_USER
                 name: postgres-secret
           - name: DB_PASSWORD
             valueFrom:
               secretKeyRef:
                 key: POSTGRES_PASSWORD
                 name: postgres-secret

         resources:
           requests:
             cpu: 250m
             memory: 256Mi
           limits:
             cpu: 500m
             memory: 512Mi
         readinessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 20
           periodSeconds: 10
         livenessProbe:
           httpGet:
             path: /
             port: 8080
           initialDelaySeconds: 40
           periodSeconds: 15


    

  
    
  
    