apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-config
  namespace: finbank-new

data:
  nginx.conf: |
    events {}

    http {

      upstream auth_service {
        server auth-service.finbank-new.svc.cluster.local:8081;
      }

      upstream monolith_service {
        server monolith.finbank-legacy.svc.cluster.local:8080;
      }

      server {

        listen 80;

        location /api/auth/ {
          proxy_pass http://auth_service;
        }

        location / {
          proxy_pass http://monolith_service;
        }

      }
    }